'use client'

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "sw" | "fr" | "es" | "de" | "pt";

interface Translations {
  [key: string]: {
    [lang in Language]: string;
  };
}

const translations: Translations = {
  // Navigation
  "nav.home": { en: "Home", sw: "Nyumbani", fr: "Accueil", es: "Inicio", de: "Startseite", pt: "Início" },
  "nav.discover": { en: "Discover Us", sw: "Gundua Sisi", fr: "Découvrez-nous", es: "Descúbrenos", de: "Entdecken Sie uns", pt: "Descubra-nos" },
  "nav.products": { en: "Workspace Solutions", sw: "Suluhisho za Nafasi", fr: "Solutions d'Espace", es: "Soluciones de Espacio", de: "Arbeitsplatzlösungen", pt: "Soluções de Espaço" },
  "nav.getstarted": { en: "Get Started", sw: "Anza", fr: "Commencer", es: "Empezar", de: "Loslegen", pt: "Começar" },
  "nav.restaurant": { en: "Restaurant", sw: "Mkahawa", fr: "Restaurant", es: "Restaurante", de: "Restaurant", pt: "Restaurante" },
  "nav.events": { en: "Events", sw: "Matukio", fr: "Événements", es: "Eventos", de: "Veranstaltungen", pt: "Eventos" },
  "nav.magazine": { en: "Magazine", sw: "Jarida", fr: "Magazine", es: "Revista", de: "Magazin", pt: "Revista" },
  
  // Common
  "common.bookNow": { en: "Book Now", sw: "Hifadhi Sasa", fr: "Réserver maintenant", es: "Reservar ahora", de: "Jetzt buchen", pt: "Reservar agora" },
  "common.learnMore": { en: "Learn More", sw: "Jifunze Zaidi", fr: "En savoir plus", es: "Saber más", de: "Mehr erfahren", pt: "Saiba mais" },
  "common.contactUs": { en: "Contact Us", sw: "Wasiliana Nasi", fr: "Contactez-nous", es: "Contáctenos", de: "Kontaktieren Sie uns", pt: "Entre em contato" },
  "common.submit": { en: "Submit", sw: "Wasilisha", fr: "Soumettre", es: "Enviar", de: "Einreichen", pt: "Enviar" },
  "common.subscribe": { en: "Subscribe", sw: "Jiandikishe", fr: "S'abonner", es: "Suscribirse", de: "Abonnieren", pt: "Subscrever" },
  
  // Hero Section
  "hero.title1": { en: "Premium Workspace in Eldoret", sw: "Nafasi ya Kazi ya Ubora Eldoret", fr: "Espace de travail premium à Eldoret", es: "Espacio de trabajo premium en Eldoret", de: "Premium-Arbeitsbereich in Eldoret", pt: "Espaço de trabalho premium em Eldoret" },
  "hero.subtitle1": { en: "Elevate your work experience in the heart of Kenya", sw: "Inua uzoefu wako wa kazi katika moyo wa Kenya", fr: "Élevez votre expérience de travail au cœur du Kenya", es: "Eleva tu experiencia laboral en el corazón de Kenia", de: "Verbessern Sie Ihre Arbeitserfahrung im Herzen Kenias", pt: "Eleve sua experiência de trabalho no coração do Quênia" },
  "hero.title2": { en: "Luxury Offices & Event Spaces", sw: "Ofisi za Kifahari na Nafasi za Matukio", fr: "Bureaux de luxe et espaces événementiels", es: "Oficinas de lujo y espacios para eventos", de: "Luxusbüros und Veranstaltungsräume", pt: "Escritórios de luxo e espaços para eventos" },
  "hero.subtitle2": { en: "Perfect for teams and entrepreneurs", sw: "Bora kwa timu na wajasiriamali", fr: "Parfait pour les équipes et les entrepreneurs", es: "Perfecto para equipos y emprendedores", de: "Perfekt für Teams und Unternehmer", pt: "Perfeito para equipes e empreendedores" },
  "hero.title3": { en: "Your Success Starts Here", sw: "Mafanikio Yako Yanaanza Hapa", fr: "Votre succès commence ici", es: "Tu éxito comienza aquí", de: "Ihr Erfolg beginnt hier", pt: "Seu sucesso começa aqui" },
  "hero.subtitle3": { en: "Join Kenya's premier business community", sw: "Jiunge na jamii ya biashara bora zaidi ya Kenya", fr: "Rejoignez la première communauté d'affaires du Kenya", es: "Únete a la principal comunidad empresarial de Kenia", de: "Werden Sie Teil von Kenias führender Geschäftsgemeinschaft", pt: "Junte-se à principal comunidade empresarial do Quênia" },
  
  // Homepage Sections
  "home.featuredSpaces": { en: "Featured Spaces", sw: "Nafasi Maalum", fr: "Espaces en vedette", es: "Espacios destacados", de: "Vorgestellte Räume", pt: "Espaços em destaque" },
  "home.exploreSpaces": { en: "Explore Our Workspace Solutions", sw: "Gundua Suluhisho Zetu za Nafasi za Kazi", fr: "Explorez nos solutions d'espace de travail", es: "Explora nuestras soluciones de espacio de trabajo", de: "Entdecken Sie unsere Workspace-Lösungen", pt: "Explore nossas soluções de espaço de trabalho" },
  "home.whyChoose": { en: "Why Choose The WorkNest?", sw: "Kwa Nini Uchague The WorkNest?", fr: "Pourquoi choisir The WorkNest?", es: "¿Por qué elegir The WorkNest?", de: "Warum The WorkNest wählen?", pt: "Por que escolher The WorkNest?" },
  "home.upcomingEvents": { en: "Upcoming Events", sw: "Matukio Yanayokuja", fr: "Événements à venir", es: "Próximos eventos", de: "Bevorstehende Veranstaltungen", pt: "Próximos eventos" },
  "home.viewAll": { en: "View All", sw: "Tazama Zote", fr: "Voir tout", es: "Ver todo", de: "Alle anzeigen", pt: "Ver tudo" },
  "home.readMore": { en: "Read More", sw: "Soma Zaidi", fr: "Lire la suite", es: "Leer más", de: "Weiterlesen", pt: "Leia mais" },
  "home.bookSpace": { en: "Book a Space", sw: "Hifadhi Nafasi", fr: "Réserver un espace", es: "Reservar un espacio", de: "Einen Raum buchen", pt: "Reservar um espaço" },
  "home.getStarted": { en: "Get Started Today", sw: "Anza Leo", fr: "Commencez aujourd'hui", es: "Comience hoy", de: "Beginnen Sie heute", pt: "Comece hoje" },
  
  // Booking Form
  "booking.selectSpace": { en: "Select Space", sw: "Chagua Nafasi", fr: "Sélectionner l'espace", es: "Seleccionar espacio", de: "Raum auswählen", pt: "Selecionar espaço" },
  "booking.checkIn": { en: "Check-in Date", sw: "Tarehe ya Kuingia", fr: "Date d'arrivée", es: "Fecha de entrada", de: "Anreisedatum", pt: "Data de entrada" },
  "booking.checkOut": { en: "Check-out Date", sw: "Tarehe ya Kutoka", fr: "Date de départ", es: "Fecha de salida", de: "Abreisedatum", pt: "Data de saída" },
  "booking.guests": { en: "Guests", sw: "Wageni", fr: "Invités", es: "Huéspedes", de: "Gäste", pt: "Hóspedes" },
  
  // Footer
  "footer.copyright": { en: "© 2025 WorkNest CoWorking space Kenya. All rights reserved.", sw: "© 2025 WorkNest CoWorking space Kenya. Haki zote zimehifadhiwa.", fr: "© 2025 Finale Workspace Kenya. Tous droits réservés.", es: "© 2025 Finale Workspace Kenya. Todos los derechos reservados.", de: "© 2025 Finale Workspace Kenya. Alle Rechte vorbehalten.", pt: "© 2025 Finale Workspace Kenya. Todos os direitos reservados." },
  "footer.termsOfService": { en: "Terms of Service", sw: "Masharti ya Huduma", fr: "Conditions d'utilisation", es: "Términos de servicio", de: "Nutzungsbedingungen", pt: "Termos de serviço" },
  "footer.privacyPolicy": { en: "Privacy Policy", sw: "Sera ya Faragha", fr: "Politique de confidentialité", es: "Política de privacidad", de: "Datenschutzrichtlinie", pt: "Política de privacidade" },
  
  // Statistics Bar
  "stats.activeMembers": { en: "Active Members", sw: "Wanachama Hai", fr: "Membres actifs", es: "Miembros activos", de: "Aktive Mitglieder", pt: "Membros ativos" },
  "stats.hotDesks": { en: "HotDesks", sw: "Madaftari ya Moto", fr: "Bureaux partagés", es: "Escritorios compartidos", de: "Hot Desks", pt: "Mesas compartilhadas" },
  "stats.dedicatedDesks": { en: "Dedicated Desks", sw: "Madaftari Maalum", fr: "Bureaux dédiés", es: "Escritorios dedicados", de: "Feste Schreibtische", pt: "Mesas dedicadas" },
  "stats.privateOffices": { en: "Private Offices", sw: "Ofisi Binafsi", fr: "Bureaux privés", es: "Oficinas privadas", de: "Private Büros", pt: "Escritórios privados" },
  "stats.meetingRooms": { en: "Meeting Rooms", sw: "Vyumba vya Mikutano", fr: "Salles de réunion", es: "Salas de reuniones", de: "Besprechungsräume", pt: "Salas de reuniões" },
  "stats.servingKenya": { en: "Serving Kenya", sw: "Tumetumikia Kenya", fr: "Au service du Kenya", es: "Sirviendo a Kenia", de: "Im Dienste Kenias", pt: "Servindo o Quênia" },
  
  // Spaces
  "spaces.privateOffices": { en: "Private Offices", sw: "Ofisi Binafsi", fr: "Bureaux privés", es: "Oficinas privadas", de: "Private Büros", pt: "Escritórios privados" },
  "spaces.privateOfficesDesc": { en: "Fully furnished lockable offices", sw: "Ofisi zilizo na samani zote na zinaweza kufungwa", fr: "Bureaux entièrement meublés et verrouillables", es: "Oficinas completamente amuebladas y con cerradura", de: "Vollständig möblierte abschließbare Büros", pt: "Escritórios totalmente mobiliados e com fechadura" },
  "spaces.meetingRooms": { en: "Meeting Rooms", sw: "Vyumba vya Mikutano", fr: "Salles de réunion", es: "Salas de reuniones", de: "Besprechungsräume", pt: "Salas de reuniões" },
  "spaces.meetingRoomsDesc": { en: "Professional meeting rooms", sw: "Vyumba vya kitaaluma vya mikutano", fr: "Salles de réunion professionnelles", es: "Salas de reuniones profesionales", de: "Professionelle Besprechungsräume", pt: "Salas de reuniões profissionais" },
  "spaces.eventSpaces": { en: "Event Spaces", sw: "Nafasi za Matukio", fr: "Espaces événementiels", es: "Espacios para eventos", de: "Veranstaltungsräume", pt: "Espaços para eventos" },
  "spaces.eventSpacesDesc": { en: "Versatile venues for workshops, launches, and celebrations", sw: "Maeneo anuwai kwa warsha, uzinduzi, na sherehe", fr: "Lieux polyvalents pour ateliers, lancements et célébrations", es: "Espacios versátiles para talleres, lanzamientos y celebraciones", de: "Vielseitige Veranstaltungsorte für Workshops, Launchs und Feiern", pt: "Espaços versáteis para workshops, lançamentos e celebrações" },
  "spaces.callPods": { en: "Call Pods", sw: "Vitengo vya Simu", fr: "Cabines d'appel", es: "Cabinas telefónicas", de: "Telefonkabinen", pt: "Cabines telefônicas" },
  "spaces.callPodsDesc": { en: "Private soundproof pods for focused calls and video meetings", sw: "Vitengo vya sauti vya kibinafsi kwa simu na mikutano ya video", fr: "Cabines insonorisées privées pour appels et visioconférences", es: "Cabinas insonorizadas privadas para llamadas y videollamadas", de: "Private schalldichte Kabinen für Anrufe und Videokonferenzen", pt: "Cabines privadas à prova de som para chamadas e videoconferências" },
  "spaces.kidsZone": { en: "Kids Zone", sw: "Eneo la Watoto", fr: "Espace enfants", es: "Zona infantil", de: "Kinderbereich", pt: "Zona infantil" },
  "spaces.kidsZoneDesc": { en: "Safe, supervised play area for your little ones", sw: "Eneo la kucheza salama na linalosimamiwa kwa watoto wako", fr: "Espace de jeu sûr et supervisé pour vos petits", es: "Área de juego segura y supervisada para sus pequeños", de: "Sicherer, beaufsichtigter Spielbereich für Ihre Kleinen", pt: "Área de brincadeira segura e supervisionada para seus pequenos" },
  "spaces.comingSoon": { en: "Coming Soon", sw: "Inakuja Hivi Karibuni", fr: "Bientôt disponible", es: "Próximamente", de: "Demnächst", pt: "Em breve" },
  "spaces.requestQuote": { en: "Request a Quote", sw: "Omba Bei", fr: "Demander un devis", es: "Solicitar cotización", de: "Angebot anfordern", pt: "Solicitar orçamento" },
  "spaces.from": { en: "From", sw: "Kuanzia", fr: "À partir de", es: "Desde", de: "Ab", pt: "A partir de" },
  
  // Price Periods
  "price.day": { en: "day", sw: "siku", fr: "jour", es: "día", de: "Tag", pt: "dia" },
  "price.hour": { en: "hour", sw: "saa", fr: "heure", es: "hora", de: "Stunde", pt: "hora" },
  "price.month": { en: "month", sw: "mwezi", fr: "mois", es: "mes", de: "Monat", pt: "mês" },
  "price.weekly": { en: "week", sw: "wiki", fr: "semaine", es: "semana", de: "Woche", pt: "semana" },
  "price.halfDay": { en: "half day", sw: "nusu siku", fr: "demi-journée", es: "medio día", de: "halber Tag", pt: "meio dia" },
  "price.hourlyRate": { en: "Hourly Rate:", sw: "Bei ya Saa:", fr: "Tarif horaire:", es: "Tarifa por hora:", de: "Stundensatz:", pt: "Tarifa por hora:" },
  "price.halfDayLabel": { en: "Half Day (4hrs):", sw: "Nusu Siku (masaa 4):", fr: "Demi-journée (4h):", es: "Medio día (4h):", de: "Halber Tag (4 Std.):", pt: "Meio dia (4h):" },
  "price.fullDayLabel": { en: "Full Day (8hrs):", sw: "Siku Nzima (masaa 8):", fr: "Journée complète (8h):", es: "Día completo (8h):", de: "Ganzer Tag (8 Std.):", pt: "Dia inteiro (8h):" },
  "price.weeklyLabel": { en: "Weekly:", sw: "Kwa Wiki:", fr: "Hebdomadaire:", es: "Semanal:", de: "Wöchentlich:", pt: "Semanal:" },
  "price.monthlyLabel": { en: "Monthly:", sw: "Kwa Mwezi:", fr: "Mensuel:", es: "Mensual:", de: "Monatlich:", pt: "Mensal:" },
  
  // Intro Section
  "intro.title": { en: "A Space Where Productivity Meets Comfort in Kenya", sw: "Nafasi Ambapo Uzalishaji Unakutana na Faraja Kenya", fr: "Un espace où productivité et confort se rencontrent au Kenya", es: "Un espacio donde la productividad se encuentra con la comodidad en Kenia", de: "Ein Raum, in dem Produktivität auf Komfort in Kenia trifft", pt: "Um espaço onde produtividade encontra conforto no Quênia" },
  "intro.description": { en: "At The WorkNest Eldoret, we redefine professional environments in Kenya's vibrant western hub. Our world-class amenities blend seamlessly with authentic Kenyan hospitality, creating spaces where businesses thrive, ideas grow, and communities flourish", sw: "Katika The WorkNest Eldoret, tunafafanua upya mazingira ya kitaaluma katika kitovu cha magharibi cha Kenya. Vifaa vyetu vya kiwango cha dunia huchanganyika kwa urahisi na ukarimu wa Kenya, na kuunda nafasi ambazo biashara zinakua, mawazo yanakua, na jamii zinastawi", fr: "Chez The WorkNest Eldoret, nous redéfinissons les environnements professionnels dans le hub occidental dynamique du Kenya. Nos équipements de classe mondiale se mélangent parfaitement avec l'hospitalité authentique kenyane, créant des espaces où les entreprises prospèrent, les idées grandissent et les communautés s'épanouissent", es: "En The WorkNest Eldoret, redefinimos los entornos profesionales en el vibrante centro occidental de Kenia. Nuestras instalaciones de clase mundial se combinan perfectamente con la auténtica hospitalidad keniana, creando espacios donde las empresas prosperan, las ideas crecen y las comunidades florecen", de: "Bei The WorkNest Eldoret definieren wir professionelle Umgebungen im lebendigen westlichen Zentrum Kenias neu. Unsere erstklassigen Einrichtungen verbinden sich nahtlos mit authentischer kenianischer Gastfreundschaft und schaffen Räume, in denen Unternehmen gedeihen, Ideen wachsen und Gemeinschaften aufblühen", pt: "No The WorkNest Eldoret, redefinimos ambientes profissionais no vibrante centro ocidental do Quênia. Nossas instalações de classe mundial se misturam perfeitamente com a autêntica hospitalidade queniana, criando espaços onde as empresas prosperam, as ideias crescem e as comunidades florescem" },
  "intro.whoWeAre": { en: "Who We Are", sw: "Sisi Ni Nani", fr: "Qui nous sommes", es: "Quiénes somos", de: "Wer wir sind", pt: "Quem somos" },
  "intro.whoWeAreDesc": { en: "The WorkNest Eldoret is a premium coworking and innovation space in Elgon View, offering flexible, executive-grade workspaces that inspire productivity, collaboration, and growth. From hot desks and private offices to meeting suites, event spaces, and a kids' zone, every detail is designed to help businesses thrive and ideas take flight.", sw: "The WorkNest Eldoret ni nafasi ya juu ya kazi pamoja na ubunifu katika Elgon View, inayotoa nafasi za kazi za kifleksiboli za kiwango cha utendaji zinazohimiza uzalishaji, ushirikiano, na ukuaji. Kutoka madaftari ya moto na ofisi binafsi hadi vyumba vya mikutano, nafasi za matukio, na eneo la watoto, kila kitu kimeundwa ili kusaidia biashara kustawi na mawazo kukua.", fr: "The WorkNest Eldoret est un espace de coworking et d'innovation premium à Elgon View, offrant des espaces de travail flexibles de niveau exécutif qui inspirent la productivité, la collaboration et la croissance. Des bureaux partagés et bureaux privés aux suites de réunion, espaces événementiels et zone enfants, chaque détail est conçu pour aider les entreprises à prospérer et les idées à prendre leur envol.", es: "The WorkNest Eldoret es un espacio premium de coworking e innovación en Elgon View, que ofrece espacios de trabajo flexibles de nivel ejecutivo que inspiran productividad, colaboración y crecimiento. Desde escritorios compartidos y oficinas privadas hasta suites de reuniones, espacios para eventos y una zona infantil, cada detalle está diseñado para ayudar a las empresas a prosperar y las ideas a despegar.", de: "The WorkNest Eldoret ist ein Premium-Coworking- und Innovationsraum in Elgon View, der flexible, auf Führungsebene ausgestattete Arbeitsplätze bietet, die Produktivität, Zusammenarbeit und Wachstum fördern. Von Hot Desks und privaten Büros bis hin zu Besprechungsräumen, Veranstaltungsräumen und einer Kinderzone ist jedes Detail darauf ausgelegt, Unternehmen zum Erfolg zu verhelfen und Ideen zum Fliegen zu bringen.", pt: "The WorkNest Eldoret é um espaço premium de coworking e inovação em Elgon View, oferecendo espaços de trabalho flexíveis de nível executivo que inspiram produtividade, colaboração e crescimento. Desde mesas compartilhadas e escritórios privados até suítes de reuniões, espaços para eventos e uma zona infantil, cada detalhe é projetado para ajudar as empresas a prosperar e as ideias a decolar." },
  "intro.ourMission": { en: "Our Mission", sw: "Lengo Letu", fr: "Notre mission", es: "Nuestra misión", de: "Unsere Mission", pt: "Nossa missão" },
  "intro.ourMissionDesc": { en: "To provide flexible, world-class workspaces that enhance productivity, foster meaningful connections, and support growth through exceptional service, modern design, and a vibrant community.", sw: "Kutoa nafasi za kazi za kifleksiboli za kiwango cha dunia zinazoboresha uzalishaji, kukuza uhusiano wa maana, na kuunga mkono ukuaji kupitia huduma bora, muundo wa kisasa, na jamii hai.", fr: "Fournir des espaces de travail flexibles de classe mondiale qui améliorent la productivité, favorisent des connexions significatives et soutiennent la croissance grâce à un service exceptionnel, un design moderne et une communauté dynamique.", es: "Proporcionar espacios de trabajo flexibles de clase mundial que mejoren la productividad, fomenten conexiones significativas y apoyen el crecimiento a través de un servicio excepcional, diseño moderno y una comunidad vibrante.", de: "Flexible, erstklassige Arbeitsplätze bereitzustellen, die die Produktivität steigern, bedeutungsvolle Verbindungen fördern und Wachstum durch außergewöhnlichen Service, modernes Design und eine lebendige Gemeinschaft unterstützen.", pt: "Fornecer espaços de trabalho flexíveis de classe mundial que aumentem a produtividade, promovam conexões significativas e apoiem o crescimento através de serviço excepcional, design moderno e uma comunidade vibrante." },
  "intro.ourVision": { en: "Our Vision", sw: "Maono Yetu", fr: "Notre vision", es: "Nuestra visión", de: "Unsere Vision", pt: "Nossa visão" },
  "intro.ourVisionDesc": { en: "To be Kenya's leading hub for innovation and collaboration empowering professionals, entrepreneurs, and businesses to thrive in a dynamic, inspiring workspace.", sw: "Kuwa kitovu kuu cha Kenya cha ubunifu na ushirikiano kinachowapa nguvu wataalamu, wajasiriamali, na biashara kustawi katika nafasi ya kazi ya kusisimua na ya kusisimua.", fr: "Être le principal centre d'innovation et de collaboration du Kenya, permettant aux professionnels, entrepreneurs et entreprises de prospérer dans un espace de travail dynamique et inspirant.", es: "Ser el centro líder de innovación y colaboración de Kenia, capacitando a profesionales, emprendedores y empresas para prosperar en un espacio de trabajo dinámico e inspirador.", de: "Kenyas führendes Zentrum für Innovation und Zusammenarbeit zu sein, das Fachkräfte, Unternehmer und Unternehmen befähigt, in einem dynamischen, inspirierenden Arbeitsplatz zu gedeihen.", pt: "Ser o principal centro de inovação e colaboração do Quênia, capacitando profissionais, empreendedores e empresas a prosperar em um espaço de trabalho dinâmico e inspirador." },
  "intro.discoverStory": { en: "Discover Our Story", sw: "Gundua Hadithi Yetu", fr: "Découvrez notre histoire", es: "Descubre nuestra historia", de: "Entdecken Sie unsere Geschichte", pt: "Descubra nossa história" },
  
  // Featured Spaces
  "spaces.discoverSolutions": { en: "From private offices to collaborative areas, discover workspace solutions designed for every need", sw: "Kutoka ofisi binafsi hadi maeneo ya ushirikiano, gundua suluhisho za nafasi za kazi zilizoundwa kwa kila hitaji", fr: "Des bureaux privés aux espaces collaboratifs, découvrez des solutions d'espace de travail conçues pour tous les besoins", es: "Desde oficinas privadas hasta áreas colaborativas, descubre soluciones de espacio de trabajo diseñadas para cada necesidad", de: "Von privaten Büros bis zu kollaborativen Bereichen, entdecken Sie Workspace-Lösungen, die für jeden Bedarf entwickelt wurden", pt: "De escritórios privados a áreas colaborativas, descubra soluções de espaço de trabalho projetadas para cada necessidade" },
  
  // Office Spaces Page
  "officeSpaces.title": { en: "Private Office Spaces in Eldoret", sw: "Nafasi za Ofisi Binafsi Eldoret", fr: "Espaces de bureaux privés à Eldoret", es: "Espacios de oficinas privadas en Eldoret", de: "Private Büroräume in Eldoret", pt: "Espaços de escritórios privados em Eldoret" },
  "officeSpaces.subtitle": { en: "Find the perfect workspace solution for your needs", sw: "Pata suluhisho bora la nafasi ya kazi kwa mahitaji yako", fr: "Trouvez la solution d'espace de travail parfaite pour vos besoins", es: "Encuentra la solución de espacio de trabajo perfecta para tus necesidades", de: "Finden Sie die perfekte Workspace-Lösung für Ihre Bedürfnisse", pt: "Encontre a solução de espaço de trabalho perfeita para suas necessidades" },
  "officeSpaces.includedAmenities": { en: "Included Amenities", sw: "Vifaa Vilivyojumuishwa", fr: "Équipements inclus", es: "Comodidades incluidas", de: "Enthaltene Ausstattung", pt: "Comodidades incluídas" },
  "officeSpaces.features": { en: "Features", sw: "Vipengele", fr: "Caractéristiques", es: "Características", de: "Merkmale", pt: "Características" },
  "officeSpaces.bookNow": { en: "Book This Space", sw: "Hifadhi Nafasi Hii", fr: "Réserver cet espace", es: "Reservar este espacio", de: "Diesen Raum buchen", pt: "Reservar este espaço" },
  "officeSpaces.hourly": { en: "Hourly", sw: "Kwa Saa", fr: "À l'heure", es: "Por hora", de: "Stündlich", pt: "Por hora" },
  "officeSpaces.halfDay": { en: "Half Day", sw: "Nusu Siku", fr: "Demi-journée", es: "Medio día", de: "Halber Tag", pt: "Meio dia" },
  "officeSpaces.fullDay": { en: "Full Day", sw: "Siku Nzima", fr: "Journée complète", es: "Día completo", de: "Ganzer Tag", pt: "Dia inteiro" },
  "officeSpaces.weekly": { en: "Weekly", sw: "Kwa Wiki", fr: "Hebdomadaire", es: "Semanal", de: "Wöchentlich", pt: "Semanal" },
  "officeSpaces.monthly": { en: "Monthly", sw: "Kwa Mwezi", fr: "Mensuel", es: "Mensual", de: "Monatlich", pt: "Mensal" },
  
  // Pricing Page
  "pricing.title": { en: "Simple, Transparent Pricing", sw: "Bei Rahisi na Wazi", fr: "Tarification simple et transparente", es: "Precios simples y transparentes", de: "Einfache, transparente Preise", pt: "Preços simples e transparentes" },
  "pricing.subtitle": { en: "Choose the plan that works best for you in Eldoret. All plans include our core amenities.", sw: "Chagua mpango unaokufaa zaidi Eldoret. Mipango yote inajumuisha vifaa vyetu vya msingi.", fr: "Choisissez le plan qui vous convient le mieux à Eldoret. Tous les plans incluent nos équipements de base.", es: "Elige el plan que mejor funcione para ti en Eldoret. Todos los planes incluyen nuestras comodidades principales.", de: "Wählen Sie den Plan, der am besten zu Ihnen passt in Eldoret. Alle Pläne beinhalten unsere Kernausstattung.", pt: "Escolha o plano que melhor funciona para você em Eldoret. Todos os planos incluem nossas comodidades principais." },
  "pricing.popular": { en: "Most Popular", sw: "Maarufu Zaidi", fr: "Le plus populaire", es: "Más popular", de: "Am beliebtesten", pt: "Mais popular" },
  "pricing.addOns": { en: "Add-Ons & Extras", sw: "Viongezi na Ziada", fr: "Suppléments et extras", es: "Complementos y extras", pt: "Complementos e extras", de: "Zusätze & Extras" },
  "pricing.free": { en: "Free", sw: "Bure", fr: "Gratuit", es: "Gratis", de: "Kostenlos", pt: "Grátis" },
  "pricing.needCustomSolution": { en: "Need a Custom Solution?", sw: "Unahitaji Suluhisho Maalum?", fr: "Besoin d'une solution personnalisée?", es: "¿Necesitas una solución personalizada?", de: "Brauchen Sie eine maßgeschneiderte Lösung?", pt: "Precisa de uma solução personalizada?" },
  "pricing.customSolutionDesc": { en: "Contact us for enterprise plans and custom workspace solutions in Eldoret", sw: "Wasiliana nasi kwa mipango ya biashara na suluhisho maalum za nafasi za kazi Eldoret", fr: "Contactez-nous pour des plans d'entreprise et des solutions d'espace de travail personnalisées à Eldoret", es: "Contáctenos para planes empresariales y soluciones de espacio de trabajo personalizadas en Eldoret", de: "Kontaktieren Sie uns für Unternehmenspläne und maßgeschneiderte Workspace-Lösungen in Eldoret", pt: "Entre em contato conosco para planos empresariais e soluções de espaço de trabalho personalizadas em Eldoret" },
  "pricing.contactSales": { en: "Contact Sales", sw: "Wasiliana na Uuzaji", fr: "Contacter les ventes", es: "Contactar ventas", de: "Vertrieb kontaktieren", pt: "Contatar vendas" },
  "price.page": { en: "page", sw: "ukurasa", fr: "page", es: "página", de: "Seite", pt: "página" },
  
  // Discover Page
  "discover.title": { en: "Discover WorkNest", sw: "Gundua WorkNest", fr: "Découvrez WorkNest", es: "Descubre WorkNest", de: "Entdecken Sie WorkNest", pt: "Descubra WorkNest" },
  "discover.subtitle": { en: "Your premier workspace partner in Eldoret, Kenya", sw: "Mshirika wako wa nafasi ya kazi Eldoret, Kenya", fr: "Votre partenaire d'espace de travail de premier plan à Eldoret, Kenya", es: "Tu socio de espacio de trabajo principal en Eldoret, Kenia", de: "Ihr führender Workspace-Partner in Eldoret, Kenia", pt: "Seu parceiro de espaço de trabalho principal em Eldoret, Quênia" },
  "discover.whoWeAre": { en: "Who We Are", sw: "Sisi Ni Nani", fr: "Qui nous sommes", es: "Quiénes somos", de: "Wer wir sind", pt: "Quem somos" },
  "discover.whoWeAreDesc1": { en: "The WorkNest is a premium coworking and innovation space in the prestigious Elgon View, Eldoret. We offer flexible, executive-grade workspace designed to boost productivity, collaboration, and business growth.", sw: "The WorkNest ni nafasi ya juu ya kazi pamoja na ubunifu katika Elgon View maarufu, Eldoret. Tunatoa nafasi ya kazi ya kifleksiboli ya kiwango cha utendaji iliyoundwa ili kuongeza uzalishaji, ushirikiano, na ukuaji wa biashara.", fr: "The WorkNest est un espace de coworking et d'innovation premium dans le prestigieux Elgon View, Eldoret. Nous offrons un espace de travail flexible de niveau exécutif conçu pour stimuler la productivité, la collaboration et la croissance des entreprises.", es: "The WorkNest es un espacio premium de coworking e innovación en el prestigioso Elgon View, Eldoret. Ofrecemos un espacio de trabajo flexible de nivel ejecutivo diseñado para impulsar la productividad, la colaboración y el crecimiento empresarial.", de: "The WorkNest ist ein Premium-Coworking- und Innovationsraum im prestigeträchtigen Elgon View, Eldoret. Wir bieten flexible, auf Führungsebene ausgestattete Arbeitsplätze, die darauf ausgelegt sind, Produktivität, Zusammenarbeit und Geschäftswachstum zu steigern.", pt: "The WorkNest é um espaço premium de coworking e inovação no prestigioso Elgon View, Eldoret. Oferecemos um espaço de trabalho flexível de nível executivo projetado para impulsionar a produtividade, colaboração e crescimento empresarial." },
  "discover.whoWeAreDesc2": { en: "Our facilities include hot desks, dedicated desks, meeting suites, event space, a lounge, an eatery, and a kids' zone all thoughtfully designed with ergonomic furniture, high-speed internet, natural light, and inspiring views.", sw: "Vifaa vyetu vinajumuisha madaftari ya moto, madaftari maalum, vyumba vya mikutano, nafasi ya matukio, chumba cha mapumziko, mkahawa, na eneo la watoto vyote vimeundwa kwa makini na samani za ergonomic, intaneti ya kasi, mwanga wa asili, na maono ya kusisimua.", fr: "Nos installations comprennent des bureaux partagés, des bureaux dédiés, des suites de réunion, un espace événementiel, un salon, un restaurant et une zone enfants, tous conçus avec soin avec du mobilier ergonomique, Internet haut débit, lumière naturelle et vues inspirantes.", es: "Nuestras instalaciones incluyen escritorios compartidos, escritorios dedicados, suites de reuniones, espacio para eventos, un salón, un comedor y una zona infantil, todos diseñados cuidadosamente con muebles ergonómicos, internet de alta velocidad, luz natural y vistas inspiradoras.", de: "Unsere Einrichtungen umfassen Hot Desks, feste Schreibtische, Besprechungsräume, Veranstaltungsräume, eine Lounge, ein Restaurant und eine Kinderzone, alle durchdacht gestaltet mit ergonomischen Möbeln, Highspeed-Internet, natürlichem Licht und inspirierenden Aussichten.", pt: "Nossas instalações incluem mesas compartilhadas, mesas dedicadas, suítes de reuniões, espaço para eventos, um lounge, um restaurante e uma zona infantil, todos projetados com cuidado com móveis ergonômicos, internet de alta velocidade, luz natural e vistas inspiradoras." },
  "discover.whoWeAreDesc3": { en: "At The WorkNest, we provide the ideal environment for businesses to thrive, teams to connect, and ideas to grow.", sw: "Katika The WorkNest, tunatoa mazingira bora kwa biashara kustawi, timu kuungana, na mawazo kukua.", fr: "Chez The WorkNest, nous fournissons l'environnement idéal pour que les entreprises prospèrent, que les équipes se connectent et que les idées grandissent.", es: "En The WorkNest, proporcionamos el entorno ideal para que las empresas prosperen, los equipos se conecten y las ideas crezcan.", de: "Bei The WorkNest schaffen wir die ideale Umgebung, damit Unternehmen gedeihen, Teams sich verbinden und Ideen wachsen können.", pt: "No The WorkNest, fornecemos o ambiente ideal para empresas prosperarem, equipes se conectarem e ideias crescerem." },
  "discover.whyChoose": { en: "Why Choose WorkNest?", sw: "Kwa Nini Uchague WorkNest?", fr: "Pourquoi choisir WorkNest?", es: "¿Por qué elegir WorkNest?", de: "Warum WorkNest wählen?", pt: "Por que escolher WorkNest?" },
  "discover.flexibility": { en: "Flexibility", sw: "Ubadilishaji", fr: "Flexibilité", es: "Flexibilidad", de: "Flexibilität", pt: "Flexibilidade" },
  "discover.flexibilityDesc": { en: "Daily, monthly, or yearly plans that adapt to your changing needs", sw: "Mipango ya kila siku, kila mwezi, au kila mwaka inayojifaa na mahitaji yako yanayobadilika", fr: "Plans quotidiens, mensuels ou annuels qui s'adaptent à vos besoins changeants", es: "Planes diarios, mensuales o anuales que se adaptan a tus necesidades cambiantes", de: "Tägliche, monatliche oder jährliche Pläne, die sich an Ihre sich ändernden Bedürfnisse anpassen", pt: "Planos diários, mensais ou anuais que se adaptam às suas necessidades em mudança" },
  "discover.premiumDesign": { en: "Premium Design", sw: "Muundo wa Juu", fr: "Design premium", es: "Diseño premium", de: "Premium-Design", pt: "Design premium" },
  "discover.premiumDesignDesc": { en: "Thoughtfully designed spaces that inspire creativity and productivity", sw: "Nafasi zilizoundwa kwa makini zinazohimiza ubunifu na uzalishaji", fr: "Espaces soigneusement conçus qui inspirent créativité et productivité", es: "Espacios cuidadosamente diseñados que inspiran creatividad y productividad", de: "Durchdacht gestaltete Räume, die Kreativität und Produktivität inspirieren", pt: "Espaços cuidadosamente projetados que inspiram criatividade e produtividade" },
  "discover.community": { en: "Community", sw: "Jamii", fr: "Communauté", es: "Comunidad", de: "Gemeinschaft", pt: "Comunidade" },
  "discover.communityDesc": { en: "Network with like-minded professionals and entrepreneurs in Eldoret", sw: "Jifunze na wataalamu na wajasiriamali walio na mawazo sawa Eldoret", fr: "Réseauter avec des professionnels et entrepreneurs partageant les mêmes idées à Eldoret", es: "Conecta con profesionales y emprendedores afines en Eldoret", de: "Netzwerken Sie mit gleichgesinnten Fachkräften und Unternehmern in Eldoret", pt: "Conecte-se com profissionais e empreendedores afins em Eldoret" },
  "discover.convenientAccess": { en: "Convenient Access Hours", sw: "Masaa ya Ufikiaji Rahisi", fr: "Heures d'accès pratiques", es: "Horas de acceso convenientes", de: "Bequeme Zugangszeiten", pt: "Horários de acesso convenientes" },
  "discover.convenientAccessDesc": { en: "Work on your schedule with flexible access", sw: "Fanya kazi kwa ratiba yako na ufikiaji wa kifleksiboli", fr: "Travaillez selon votre emploi du temps avec un accès flexible", es: "Trabaja según tu horario con acceso flexible", de: "Arbeiten Sie nach Ihrem Zeitplan mit flexiblem Zugang", pt: "Trabalhe no seu horário com acesso flexível" },
  "discover.whatWeOffer": { en: "What We Offer", sw: "Tunachotoa", fr: "Ce que nous offrons", es: "Lo que ofrecemos", de: "Was wir anbieten", pt: "O que oferecemos" },
  "discover.hotDeskDedicated": { en: "Hot Desk and Dedicated Desks", sw: "Madaftari ya Moto na Maalum", fr: "Bureaux partagés et dédiés", es: "Escritorios compartidos y dedicados", de: "Hot Desks und feste Schreibtische", pt: "Mesas compartilhadas e dedicadas" },
  "discover.hotDeskDedicatedDesc": { en: "Flexible seating in shared spaces", sw: "Kiti cha kifleksiboli katika nafasi za pamoja", fr: "Sièges flexibles dans des espaces partagés", es: "Asientos flexibles en espacios compartidos", de: "Flexible Sitzplätze in Gemeinschaftsräumen", pt: "Assentos flexíveis em espaços compartilhados" },
  "discover.privateOffices": { en: "Private Offices", sw: "Ofisi Binafsi", fr: "Bureaux privés", es: "Oficinas privadas", de: "Private Büros", pt: "Escritórios privados" },
  "discover.privateOfficesDesc": { en: "Fully furnished lockable office", sw: "Ofisi iliyokamilika na inayoweza kufungwa", fr: "Bureau entièrement meublé et verrouillable", es: "Oficina completamente amueblada y con cerradura", de: "Vollständig möbliertes abschließbares Büro", pt: "Escritório totalmente mobiliado e com fechadura" },
  "discover.meetingRooms": { en: "Meeting Rooms", sw: "Vyumba vya Mikutano", fr: "Salles de réunion", es: "Salas de reuniones", de: "Besprechungsräume", pt: "Salas de reuniões" },
  "discover.meetingRoomsDesc": { en: "Professional boardrooms", sw: "Vyumba vya kitaaluma vya mikutano", fr: "Salles de réunion professionnelles", es: "Salas de reuniones profesionales", de: "Professionelle Besprechungsräume", pt: "Salas de reuniões profissionais" },
  "discover.eventSpace": { en: "Event Space", sw: "Nafasi ya Matukio", fr: "Espace événementiel", es: "Espacio para eventos", de: "Veranstaltungsraum", pt: "Espaço para eventos" },
  "discover.eventSpaceDesc": { en: "Venues for workshops and launches", sw: "Maeneo ya warsha na uzinduzi", fr: "Lieux pour ateliers et lancements", es: "Espacios para talleres y lanzamientos", de: "Veranstaltungsorte für Workshops und Launchs", pt: "Espaços para workshops e lançamentos" },
  "discover.restaurantCafe": { en: "Restaurant & Café", sw: "Mkahawa na Kahawa", fr: "Restaurant et café", es: "Restaurante y café", de: "Restaurant & Café", pt: "Restaurante e café" },
  "discover.restaurantCafeDesc": { en: "On-site dining and refreshments", sw: "Chakula na vinywaji kwenye tovuti", fr: "Restauration et rafraîchissements sur place", es: "Comida y refrescos en el lugar", de: "Essen und Erfrischungen vor Ort", pt: "Refeições e refrescos no local" },
  "discover.kidsZone": { en: "Kids Zone", sw: "Eneo la Watoto", fr: "Espace enfants", es: "Zona infantil", de: "Kinderbereich", pt: "Zona infantil" },
  "discover.kidsZoneDesc": { en: "Supervised childcare facility", sw: "Kituo cha watoto kinachosimamiwa", fr: "Installation de garde d'enfants supervisée", es: "Instalación de cuidado infantil supervisado", de: "Betreute Kindereinrichtung", pt: "Instalação de cuidado infantil supervisionado" },
  "discover.highSpeedWifi": { en: "High-Speed WiFi", sw: "WiFi ya Kasi", fr: "WiFi haute vitesse", es: "WiFi de alta velocidad", de: "Highspeed-WiFi", pt: "WiFi de alta velocidade" },
  "discover.highSpeedWifiDesc": { en: "100Mbps+ internet throughout", sw: "Intaneti ya 100Mbps+ kila mahali", fr: "Internet 100Mbps+ partout", es: "Internet de 100Mbps+ en todas partes", de: "100Mbps+ Internet überall", pt: "Internet de 100Mbps+ em todos os lugares" },
  "discover.freeParking": { en: "Free Ample Parking On Site", sw: "Maeneo ya Bure ya Kuegesha Gari Kwenye Tovuti", fr: "Parking gratuit et spacieux sur place", es: "Estacionamiento amplio y gratuito en el lugar", de: "Kostenlose, geräumige Parkplätze vor Ort", pt: "Estacionamento amplo e gratuito no local" },
  "discover.freeParkingDesc": { en: "Secure parking for members", sw: "Maeneo salama ya kuegesha gari kwa wanachama", fr: "Parking sécurisé pour les membres", es: "Estacionamiento seguro para miembros", de: "Sichere Parkplätze für Mitglieder", pt: "Estacionamento seguro para membros" },
  "discover.readyToExperience": { en: "Ready to Experience WorkNest?", sw: "Tayari Kujaribu WorkNest?", fr: "Prêt à découvrir WorkNest?", es: "¿Listo para experimentar WorkNest?", de: "Bereit, WorkNest zu erleben?", pt: "Pronto para experimentar o WorkNest?" },
  "discover.readyDescription": { en: "Schedule a tour and see why Eldoret's top professionals choose WorkNest", sw: "Panga ziara na uone kwa nini wataalamu wa juu wa Eldoret wanachagua WorkNest", fr: "Planifiez une visite et découvrez pourquoi les meilleurs professionnels d'Eldoret choisissent WorkNest", es: "Programa una visita y descubre por qué los mejores profesionales de Eldoret eligen WorkNest", de: "Planen Sie eine Tour und sehen Sie, warum Eldorets Top-Profis WorkNest wählen", pt: "Agende uma visita e veja por que os principais profissionais de Eldoret escolhem o WorkNest" },
  "discover.bookTour": { en: "Book a Tour", sw: "Hifadhi Ziara", fr: "Réserver une visite", es: "Reservar una visita", de: "Tour buchen", pt: "Reservar uma visita" },
  "discover.viewPricing": { en: "View Pricing", sw: "Tazama Bei", fr: "Voir les tarifs", es: "Ver precios", de: "Preise anzeigen", pt: "Ver preços" },
  
  // Boardrooms Page
  "boardrooms.title": { en: "Professional Boardrooms in Eldoret", sw: "Vyumba vya Kitaaluma vya Mikutano Eldoret", fr: "Salles de réunion professionnelles à Eldoret", es: "Salas de reuniones profesionales en Eldoret", de: "Professionelle Besprechungsräume in Eldoret", pt: "Salas de reuniões profissionais em Eldoret" },
  "boardrooms.subtitle": { en: "State-of-the-art meeting rooms designed for presentations, client meetings, and important discussions", sw: "Vyumba vya kisasa vya mikutano vilivyoundwa kwa mawasilisho, mikutano ya wateja, na mazungumzo muhimu", fr: "Salles de réunion de pointe conçues pour les présentations, les réunions clients et les discussions importantes", es: "Salas de reuniones de última generación diseñadas para presentaciones, reuniones con clientes y discusiones importantes", de: "Hochmoderne Besprechungsräume für Präsentationen, Kundengespräche und wichtige Diskussionen", pt: "Salas de reuniões de última geração projetadas para apresentações, reuniões com clientes e discussões importantes" },
  "boardrooms.premiumMeetingSpaces": { en: "Premium Meeting Spaces", sw: "Nafasi za Juu za Mikutano", fr: "Espaces de réunion premium", es: "Espacios de reunión premium", de: "Premium-Besprechungsräume", pt: "Espaços de reunião premium" },
  "boardrooms.impressClients": { en: "Impress Clients, Close Deals", sw: "Vutia Wateja, Funga Miamala", fr: "Impressionnez les clients, concluez des affaires", es: "Impresiona a los clientes, cierra tratos", de: "Beeindrucken Sie Kunden, schließen Sie Geschäfte ab", pt: "Impressione clientes, feche negócios" },
  "boardrooms.introDescription": { en: "Our fully-equipped boardrooms provide the perfect setting for board meetings, client presentations, team workshops, and important discussions. Book by the hour, half-day, or full day with all amenities included.", sw: "Vyumba vyetu vya mikutano vilivyo na vifaa vyote hutoa mazingira bora kwa mikutano ya bodi, mawasilisho ya wateja, warsha za timu, na mazungumzo muhimu. Hifadhi kwa saa, nusu siku, au siku nzima na vifaa vyote vimejumuishwa.", fr: "Nos salles de réunion entièrement équipées offrent le cadre parfait pour les réunions de conseil, les présentations clients, les ateliers d'équipe et les discussions importantes. Réservez à l'heure, à la demi-journée ou à la journée complète avec tous les équipements inclus.", es: "Nuestras salas de reuniones totalmente equipadas proporcionan el entorno perfecto para reuniones de directorio, presentaciones a clientes, talleres de equipo y discusiones importantes. Reserve por hora, medio día o día completo con todas las comodidades incluidas.", de: "Unsere voll ausgestatteten Besprechungsräume bieten die perfekte Umgebung für Vorstandssitzungen, Kundenpräsentationen, Teamworkshops und wichtige Diskussionen. Buchen Sie stundenweise, halbtags oder ganztags mit allen Einrichtungen inklusive.", pt: "Nossas salas de reuniões totalmente equipadas fornecem o ambiente perfeito para reuniões de diretoria, apresentações a clientes, workshops de equipe e discussões importantes. Reserve por hora, meio dia ou dia inteiro com todas as comodidades incluídas." },
  "boardrooms.chooseMeetingSpace": { en: "Choose Your Meeting Space", sw: "Chagua Nafasi Yako ya Mikutano", fr: "Choisissez votre espace de réunion", es: "Elige tu espacio de reunión", de: "Wählen Sie Ihren Besprechungsraum", pt: "Escolha seu espaço de reunião" },
  "boardrooms.everythingYouNeed": { en: "Everything You Need", sw: "Kila Kitu Unachohitaji", fr: "Tout ce dont vous avez besoin", es: "Todo lo que necesitas", de: "Alles was Sie brauchen", pt: "Tudo o que você precisa" },
  "boardrooms.bookBoardroom": { en: "Book Your Boardroom", sw: "Hifadhi Chumba Chako cha Mikutano", fr: "Réservez votre salle de réunion", es: "Reserva tu sala de reuniones", de: "Buchen Sie Ihren Besprechungsraum", pt: "Reserve sua sala de reuniões" },
  "boardrooms.bookDescription": { en: "Reserve your preferred meeting space today. Our team will confirm availability and prepare the room to your specifications.", sw: "Hifadhi nafasi yako ya mikutano leo. Timu yetu itathibitisha upatikanaji na kuandaa chumba kulingana na maelezo yako.", fr: "Réservez votre espace de réunion préféré aujourd'hui. Notre équipe confirmera la disponibilité et préparera la salle selon vos spécifications.", es: "Reserve su espacio de reunión preferido hoy. Nuestro equipo confirmará la disponibilidad y preparará la sala según sus especificaciones.", de: "Reservieren Sie noch heute Ihren bevorzugten Besprechungsraum. Unser Team bestätigt die Verfügbarkeit und bereitet den Raum nach Ihren Vorgaben vor.", pt: "Reserve seu espaço de reunião preferido hoje. Nossa equipe confirmará a disponibilidade e preparará a sala de acordo com suas especificações." },
  "boardrooms.needHelp": { en: "Need Help Choosing?", sw: "Unahitaji Msaada wa Kuchagua?", fr: "Besoin d'aide pour choisir?", es: "¿Necesitas ayuda para elegir?", de: "Brauchen Sie Hilfe bei der Auswahl?", pt: "Precisa de ajuda para escolher?" },
  "boardrooms.helpDescription": { en: "Our team can help you select the perfect boardroom for your meeting needs and provide custom setup options.", sw: "Timu yetu inaweza kukusaidia kuchagua chumba bora cha mikutano kwa mahitaji yako ya mikutano na kutoa chaguzi za usanidi maalum.", fr: "Notre équipe peut vous aider à sélectionner la salle de réunion parfaite pour vos besoins et fournir des options de configuration personnalisées.", es: "Nuestro equipo puede ayudarle a seleccionar la sala de reuniones perfecta para sus necesidades y proporcionar opciones de configuración personalizadas.", de: "Unser Team kann Ihnen helfen, den perfekten Besprechungsraum für Ihre Bedürfnisse auszuwählen und bietet individuelle Einrichtungsoptionen.", pt: "Nossa equipe pode ajudá-lo a selecionar a sala de reuniões perfeita para suas necessidades e fornecer opções de configuração personalizadas." },
  "boardrooms.scheduleTour": { en: "Schedule a Tour", sw: "Panga Ziara", fr: "Planifier une visite", es: "Programar una visita", de: "Tour planen", pt: "Agendar uma visita" },
  "boardrooms.capacity": { en: "Capacity", sw: "Uwezo", fr: "Capacité", es: "Capacidad", de: "Kapazität", pt: "Capacidade" },
  "boardrooms.people": { en: "people", sw: "watu", fr: "personnes", es: "personas", de: "Personen", pt: "pessoas" },
  
  // Event Spaces Page
  "eventSpaces.title": { en: "Event Spaces in Eldoret", sw: "Nafasi za Matukio Eldoret", fr: "Espaces événementiels à Eldoret", es: "Espacios para eventos en Eldoret", de: "Veranstaltungsräume in Eldoret", pt: "Espaços para eventos em Eldoret" },
  "eventSpaces.subtitle": { en: "Host unforgettable events in our versatile spaces", sw: "Andaa matukio yasiyosahaulika katika nafasi zetu anuwai", fr: "Organisez des événements inoubliables dans nos espaces polyvalents", es: "Organiza eventos inolvidables en nuestros espacios versátiles", de: "Veranstalten Sie unvergessliche Events in unseren vielseitigen Räumen", pt: "Organize eventos inesquecíveis em nossos espaços versáteis" },
  "eventSpaces.allEvents": { en: "All Events", sw: "Matukio Yote", fr: "Tous les événements", es: "Todos los eventos", de: "Alle Veranstaltungen", pt: "Todos os eventos" },
  "eventSpaces.corporateEvents": { en: "Corporate Events", sw: "Matukio ya Kikampuni", fr: "Événements d'entreprise", es: "Eventos corporativos", de: "Firmenveranstaltungen", pt: "Eventos corporativos" },
  "eventSpaces.workshopsTraining": { en: "Workshops & Training", sw: "Warsha na Mafunzo", fr: "Ateliers et formation", es: "Talleres y capacitación", de: "Workshops & Schulungen", pt: "Workshops e treinamentos" },
  "eventSpaces.conferences": { en: "Conferences", sw: "Mikutano", fr: "Conférences", es: "Conferencias", de: "Konferenzen", pt: "Conferências" },
  "eventSpaces.socialEvents": { en: "Social Events", sw: "Matukio ya Kijamii", fr: "Événements sociaux", es: "Eventos sociales", de: "Gesellschaftliche Veranstaltungen", pt: "Eventos sociais" },
  "eventSpaces.awardCeremonies": { en: "Award Ceremonies", sw: "Sherehe za Tuzo", fr: "Cérémonies de remise de prix", es: "Ceremonias de premios", de: "Preisverleihungen", pt: "Cerimônias de premiação" },
  "eventSpaces.eventsWeHost": { en: "Events We Host", sw: "Matukio Tunayoandaa", fr: "Événements que nous organisons", es: "Eventos que organizamos", de: "Veranstaltungen die wir ausrichten", pt: "Eventos que organizamos" },
  "eventSpaces.whatsIncluded": { en: "What's Included", sw: "Nini Kimejumuishwa", fr: "Ce qui est inclus", es: "Qué está incluido", de: "Was ist enthalten", pt: "O que está incluído" },
  "eventSpaces.requestQuote": { en: "Request a Quote", sw: "Omba Bei", fr: "Demander un devis", es: "Solicitar cotización", de: "Angebot anfordern", pt: "Solicitar orçamento" },
  "eventSpaces.whatTypeOfEvent": { en: "What Type of Event Are You Planning?", sw: "Ni Aina Gani ya Tukio Unaloandaa?", fr: "Quel type d'événement planifiez-vous?", es: "¿Qué tipo de evento estás planeando?", de: "Welche Art von Veranstaltung planen Sie?", pt: "Que tipo de evento você está planejando?" },
  "eventSpaces.premiumEventVenues": { en: "Premium Event Venues", sw: "Maeneo ya Juu ya Matukio", fr: "Lieux d'événements premium", es: "Espacios para eventos premium", de: "Premium-Veranstaltungsorte", pt: "Espaços para eventos premium" },
  
  // Get Started Page
  "getStarted.title": { en: "Begin Your Workspace Journey", sw: "Anza Safari Yako ya Nafasi ya Kazi", fr: "Commencez votre parcours d'espace de travail", es: "Comienza tu viaje de espacio de trabajo", de: "Beginnen Sie Ihre Workspace-Reise", pt: "Comece sua jornada de espaço de trabalho" },
  "getStarted.subtitle": { en: "Join Eldoret's premier business community and take your work to the next level", sw: "Jiunge na jamii ya biashara bora zaidi ya Eldoret na kuinua kazi yako kwa kiwango cha juu", fr: "Rejoignez la première communauté d'affaires d'Eldoret et faites passer votre travail au niveau supérieur", es: "Únete a la principal comunidad empresarial de Eldoret y lleva tu trabajo al siguiente nivel", de: "Werden Sie Teil von Eldorets führender Geschäftsgemeinschaft und bringen Sie Ihre Arbeit auf die nächste Stufe", pt: "Junte-se à principal comunidade empresarial de Eldoret e leve seu trabalho para o próximo nível" },
  "getStarted.welcome": { en: "Welcome to WorkNest", sw: "Karibu WorkNest", fr: "Bienvenue à WorkNest", es: "Bienvenido a WorkNest", de: "Willkommen bei WorkNest", pt: "Bem-vindo ao WorkNest" },
  "getStarted.welcomeDesc1": { en: "We're thrilled that you're considering joining our community of innovative professionals, entrepreneurs, and growing businesses in Eldoret. Getting started is easy choose the path that's right for you.", sw: "Tunafurahi kuwa unazingatia kujiunga na jamii yetu ya wataalamu wa ubunifu, wajasiriamali, na biashara zinazokua Eldoret. Kuanza ni rahisi chagua njia inayokufaa.", fr: "Nous sommes ravis que vous envisagiez de rejoindre notre communauté de professionnels innovants, d'entrepreneurs et d'entreprises en croissance à Eldoret. Commencer est facile, choisissez le chemin qui vous convient.", es: "Estamos encantados de que estés considerando unirte a nuestra comunidad de profesionales innovadores, emprendedores y empresas en crecimiento en Eldoret. Empezar es fácil, elige el camino que sea adecuado para ti.", de: "Wir freuen uns, dass Sie erwägen, unserer Gemeinschaft innovativer Fachkräfte, Unternehmer und wachsender Unternehmen in Eldoret beizutreten. Der Einstieg ist einfach, wählen Sie den Weg, der zu Ihnen passt.", pt: "Estamos empolgados por você estar considerando se juntar à nossa comunidade de profissionais inovadores, empreendedores e empresas em crescimento em Eldoret. Começar é fácil, escolha o caminho certo para você." },
  "getStarted.welcomeDesc2": { en: "Whether you need a dedicated office, a space for events, or want to be part of Kenya's most dynamic coworking community, we're here to support your journey every step of the way.", sw: "Iwe unahitaji ofisi maalum, nafasi ya matukio, au unataka kuwa sehemu ya jamii ya kazi pamoja yenye nguvu zaidi ya Kenya, tuko hapa kukusaidia katika safari yako kila hatua.", fr: "Que vous ayez besoin d'un bureau dédié, d'un espace pour événements, ou que vous souhaitiez faire partie de la communauté de coworking la plus dynamique du Kenya, nous sommes là pour soutenir votre parcours à chaque étape.", es: "Ya sea que necesites una oficina dedicada, un espacio para eventos, o quieras ser parte de la comunidad de coworking más dinámica de Kenia, estamos aquí para apoyar tu viaje en cada paso.", de: "Ob Sie ein festes Büro, einen Veranstaltungsraum benötigen oder Teil der dynamischsten Coworking-Gemeinschaft Kenias sein möchten, wir sind hier, um Ihre Reise in jedem Schritt zu unterstützen.", pt: "Se você precisa de um escritório dedicado, um espaço para eventos ou quer fazer parte da comunidade de coworking mais dinâmica do Quênia, estamos aqui para apoiar sua jornada a cada passo." },
  "getStarted.bookSpace": { en: "Book a Space", sw: "Hifadhi Nafasi", fr: "Réserver un espace", es: "Reservar un espacio", de: "Einen Raum buchen", pt: "Reservar um espaço" },
  "getStarted.bookSpaceDesc": { en: "Find the perfect workspace solution for your needs in Eldoret. From private offices to shared desks, we have options for everyone.", sw: "Pata suluhisho bora la nafasi ya kazi kwa mahitaji yako Eldoret. Kutoka ofisi binafsi hadi madaftari ya pamoja, tuna chaguzi kwa kila mtu.", fr: "Trouvez la solution d'espace de travail parfaite pour vos besoins à Eldoret. Des bureaux privés aux bureaux partagés, nous avons des options pour tous.", es: "Encuentra la solución de espacio de trabajo perfecta para tus necesidades en Eldoret. Desde oficinas privadas hasta escritorios compartidos, tenemos opciones para todos.", de: "Finden Sie die perfekte Workspace-Lösung für Ihre Bedürfnisse in Eldoret. Von privaten Büros bis zu geteilten Schreibtischen haben wir Optionen für jeden.", pt: "Encontre a solução de espaço de trabalho perfeita para suas necessidades em Eldoret. De escritórios privados a mesas compartilhadas, temos opções para todos." },
  "getStarted.browseSpaces": { en: "Browse Spaces", sw: "Vinjari Nafasi", fr: "Parcourir les espaces", es: "Explorar espacios", de: "Räume durchsuchen", pt: "Explorar espaços" },
  "getStarted.hostEvent": { en: "Host an Event", sw: "Andaa Tukio", fr: "Organiser un événement", es: "Organizar un evento", de: "Eine Veranstaltung ausrichten", pt: "Organizar um evento" },
  "getStarted.hostEventDesc": { en: "Our event spaces in Eldoret are perfect for conferences, workshops, product launches, and corporate gatherings of all sizes.", sw: "Nafasi zetu za matukio Eldoret ni bora kwa mikutano, warsha, uzinduzi wa bidhaa, na mikutano ya kikampuni ya ukubwa wowote.", fr: "Nos espaces événementiels à Eldoret sont parfaits pour les conférences, ateliers, lancements de produits et rassemblements d'entreprise de toutes tailles.", es: "Nuestros espacios para eventos en Eldoret son perfectos para conferencias, talleres, lanzamientos de productos y reuniones corporativas de todos los tamaños.", de: "Unsere Veranstaltungsräume in Eldoret sind perfekt für Konferenzen, Workshops, Produktlaunchs und Firmenveranstaltungen aller Größen.", pt: "Nossos espaços para eventos em Eldoret são perfeitos para conferências, workshops, lançamentos de produtos e reuniões corporativas de todos os tamanhos." },
  "getStarted.viewEvents": { en: "View Event Spaces", sw: "Tazama Nafasi za Matukio", fr: "Voir les espaces événementiels", es: "Ver espacios para eventos", de: "Veranstaltungsräume anzeigen", pt: "Ver espaços para eventos" },
  "getStarted.scheduleTour": { en: "Schedule a Tour", sw: "Panga Ziara", fr: "Planifier une visite", es: "Programar una visita", de: "Tour planen", pt: "Agendar uma visita" },
  "getStarted.scheduleTourDesc": { en: "See our spaces in person and experience the WorkNest environment. Our team will show you around and answer all your questions.", sw: "Tazama nafasi zetu mwenyewe na ujione mazingira ya WorkNest. Timu yetu itakuonyesha na kujibu maswali yako yote.", fr: "Découvrez nos espaces en personne et découvrez l'environnement WorkNest. Notre équipe vous fera visiter et répondra à toutes vos questions.", es: "Ve nuestros espacios en persona y experimenta el entorno WorkNest. Nuestro equipo te mostrará y responderá todas tus preguntas.", de: "Sehen Sie unsere Räume persönlich und erleben Sie die WorkNest-Umgebung. Unser Team führt Sie herum und beantwortet alle Ihre Fragen.", pt: "Veja nossos espaços pessoalmente e experimente o ambiente WorkNest. Nossa equipe mostrará e responderá todas as suas perguntas." },
  "getStarted.chooseSpace": { en: "Choose Your Space", sw: "Chagua Nafasi Yako", fr: "Choisissez votre espace", es: "Elige tu espacio", de: "Wählen Sie Ihren Raum", pt: "Escolha seu espaço" },
  "getStarted.chooseSpaceDesc": { en: "Browse our flexible workspace options and find the perfect fit for your needs", sw: "Vinjari chaguzi zetu za nafasi za kazi za kifleksiboli na upate inayokufaa kwa mahitaji yako", fr: "Parcourez nos options d'espace de travail flexibles et trouvez celle qui vous convient parfaitement", es: "Explora nuestras opciones de espacio de trabajo flexibles y encuentra la perfecta para tus necesidades", de: "Durchsuchen Sie unsere flexiblen Workspace-Optionen und finden Sie die perfekte für Ihre Bedürfnisse", pt: "Explore nossas opções de espaço de trabalho flexíveis e encontre a perfeita para suas necessidades" },
  "getStarted.selectPlan": { en: "Select Your Plan", sw: "Chagua Mpango Wako", fr: "Sélectionnez votre plan", es: "Selecciona tu plan", de: "Wählen Sie Ihren Plan", pt: "Selecione seu plano" },
  "getStarted.selectPlanDesc": { en: "Pick the membership plan that works best for your schedule and budget", sw: "Chagua mpango wa uanachama unaokufaa zaidi kwa ratiba yako na bajeti", fr: "Choisissez le plan d'adhésion qui convient le mieux à votre emploi du temps et à votre budget", es: "Elige el plan de membresía que mejor funcione para tu horario y presupuesto", de: "Wählen Sie den Mitgliedschaftsplan, der am besten zu Ihrem Zeitplan und Budget passt", pt: "Escolha o plano de assinatura que melhor funciona para seu horário e orçamento" },
  "getStarted.moveIn": { en: "Move In & Thrive", sw: "Ingia na Ustawi", fr: "Emménagez et prospérez", es: "Muévete y prospera", de: "Einziehen und gedeihen", pt: "Mude e prospere" },
  "getStarted.moveInDesc": { en: "Get your access, set up your space, and start working in your new home", sw: "Pata ufikiaji wako, sanidi nafasi yako, na anza kufanya kazi katika nyumba yako mpya", fr: "Obtenez votre accès, configurez votre espace et commencez à travailler dans votre nouveau domicile", es: "Obtén tu acceso, configura tu espacio y comienza a trabajar en tu nuevo hogar", de: "Erhalten Sie Ihren Zugang, richten Sie Ihren Raum ein und beginnen Sie in Ihrem neuen Zuhause zu arbeiten", pt: "Obtenha seu acesso, configure seu espaço e comece a trabalhar em sua nova casa" },
  "getStarted.viewPricingDesc": { en: "Explore our transparent pricing plans and find a membership that fits your budget. No hidden fees, just great value.", sw: "Gundua mipango yetu ya bei wazi na upate uanachama unaokufaa kwa bajeti yako. Hakuna malipo ya siri, thamani kubwa tu.", fr: "Explorez nos plans tarifaires transparents et trouvez un abonnement qui correspond à votre budget. Pas de frais cachés, juste une excellente valeur.", es: "Explora nuestros planes de precios transparentes y encuentra una membresía que se ajuste a tu presupuesto. Sin tarifas ocultas, solo gran valor.", de: "Erkunden Sie unsere transparenten Preispläne und finden Sie eine Mitgliedschaft, die zu Ihrem Budget passt. Keine versteckten Gebühren, nur großartiger Wert.", pt: "Explore nossos planos de preços transparentes e encontre uma assinatura que se ajuste ao seu orçamento. Sem taxas ocultas, apenas ótimo valor." },
  
  // Contact Page
  "contact.title": { en: "Get In Touch", sw: "Wasiliana Nasi", fr: "Contactez-nous", es: "Póngase en contacto", de: "Kontakt aufnehmen", pt: "Entre em contato" },
  "contact.subtitle": { en: "Have questions? We'd love to hear from you. Send us a message and we'll respond as soon as possible.", sw: "Una maswali? Tunapenda kusikia kutoka kwako. Tutumie ujumbe na tutajibu haraka iwezekanavyo.", fr: "Des questions? Nous aimerions avoir de vos nouvelles. Envoyez-nous un message et nous répondrons dès que possible.", es: "¿Tienes preguntas? Nos encantaría saber de ti. Envíanos un mensaje y responderemos lo antes posible.", de: "Haben Sie Fragen? Wir würden gerne von Ihnen hören. Senden Sie uns eine Nachricht und wir werden so schnell wie möglich antworten.", pt: "Tem perguntas? Adoraríamos ouvir de você. Envie-nos uma mensagem e responderemos o mais rápido possível." },
  "contact.responseTime": { en: "Response time: Within 1 hours", sw: "Muda wa kujibu: Ndani ya masaa 1", fr: "Temps de réponse: Dans 1 heure", es: "Tiempo de respuesta: Dentro de 1 hora", de: "Antwortzeit: Innerhalb von 1 Stunde", pt: "Tempo de resposta: Dentro de 1 hora" },
  "contact.phone": { en: "Phone", sw: "Simu", fr: "Téléphone", es: "Teléfono", de: "Telefon", pt: "Telefone" },
  "contact.email": { en: "Email", sw: "Barua Pepe", fr: "E-mail", es: "Correo electrónico", de: "E-Mail", pt: "E-mail" },
  "contact.address": { en: "Address", sw: "Anwani", fr: "Adresse", es: "Dirección", de: "Adresse", pt: "Endereço" },
  "contact.sendMessage": { en: "Send Us a Message", sw: "Tutume Ujumbe", fr: "Envoyez-nous un message", es: "Envíanos un mensaje", de: "Senden Sie uns eine Nachricht", pt: "Envie-nos uma mensagem" },
  "contact.name": { en: "Full Name", sw: "Jina Kamili", fr: "Nom complet", es: "Nombre completo", de: "Vollständiger Name", pt: "Nome completo" },
  "contact.subject": { en: "Subject", sw: "Somo", fr: "Sujet", es: "Asunto", de: "Betreff", pt: "Assunto" },
  "contact.message": { en: "Message", sw: "Ujumbe", fr: "Message", es: "Mensaje", de: "Nachricht", pt: "Mensagem" },
  "contact.messageSent": { en: "Message sent! We'll get back to you shortly.", sw: "Ujumbe umetumwa! Tutakujibu hivi karibuni.", fr: "Message envoyé! Nous vous répondrons sous peu.", es: "¡Mensaje enviado! Te responderemos en breve.", de: "Nachricht gesendet! Wir werden uns in Kürze bei Ihnen melden.", pt: "Mensagem enviada! Entraremos em contato em breve." },
  
  // Common translations used across pages
  "common.bookNow": { en: "Book Now", sw: "Hifadhi Sasa", fr: "Réserver maintenant", es: "Reservar ahora", de: "Jetzt buchen", pt: "Reservar agora" },
  "common.contactUs": { en: "Contact Us", sw: "Wasiliana Nasi", fr: "Contactez-nous", es: "Contáctanos", de: "Kontaktieren Sie uns", pt: "Entre em contato" },
  "common.getStarted": { en: "Get Started", sw: "Anza", fr: "Commencer", es: "Comenzar", de: "Loslegen", pt: "Começar" },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");
  const [isLoaded, setIsLoaded] = useState(false);

  // Load language from localStorage on mount
  useEffect(() => {
    const saved = localStorage.getItem('worknest-language') as Language;
    if (saved && ['en', 'sw', 'fr', 'es', 'de', 'pt'].includes(saved)) {
      setLanguageState(saved);
    }
    setIsLoaded(true);
  }, []);

  // Save language to localStorage when it changes
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('worknest-language', lang);
  };

  const t = (key: string): string => {
    return translations[key]?.[language] || key;
  };

  // Don't render until language is loaded from localStorage
  if (!isLoaded) {
    return null;
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

